[package]
name = "helm"
version = "0.1.0"
description = "带本地AI Agent的SSH终端工具：你掌舵，AI执行"
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
russh = "0.44"
russh-keys = "0.44"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
futures-util = "0.3"
serde_yaml = "0.9"
regex = "1"
anyhow = "1"
dirs = "5"
async-trait = "0.1"
data-encoding = "2"
russh-sftp = "2.4.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = ["Win32_Security_Cryptography", "Win32_Foundation"] }

[profile.release]
lto = true
